### ISSUE TITLE
Build windows binary for recommendation algorithm.

### ISSUE THREAD

**Issue by dongwookim-ml** [arongdari/flickr-photo#19]
Need windows system....

**Comment by cdawei** [comment]
There's an issue which prevents building windows binaries:
- current pickled model requires python 3.5.3
- ssvm depends on cvxopt, which only works with python 3.4 on windows http://cvxopt.org/install/index.html#windows

I suggest we add platform requirement: MacOS or Linux.

**Comment by dongwookim-ml** [comment]
I'll update the readme file, and close this issue for now.
