### ISSUE TITLE
yfcc100m & filtering_bigbox.py

### ISSUE THREAD

**Issue by jakobzhao** [arongdari/flickr-photo#20]
In your "Trajectory Construction" tutorial, you mentioned the file "YFCC100M_DATA_FILE " as a param for filtering_bigbox.py. I am wondering which YFCC100M_DATA_FIL  you indicated?
It is the one named after "YFCC100M_Place.bz2" or "YFCC100M_databset.bz2"?

Thank you!

Bo

**Comment by cdawei** [comment]
Hi Bo,

YFCC100M_DATA_FILE refers to the original YFCC100M dataset file released by Yahoo, as described [here](https://webscope.sandbox.yahoo.com/catalog.php?datatype=i&did=67).

Regards,
Dawei

**Comment by jakobzhao** [comment]
Great, thank you, Dawei!
